
insert into INVENTORY(INV_DESC,INV_NAME)VALUES('DVYDD','PHYssSICS LAB');
insert into INVENTORY(INV_DESC,INV_NAME)VALUES('DVdbhbdD','PHYsdkjndsSICS LAB');
INSERT INTO ITEMS VALUES(1,'THERMOMETER',20,1);